name: 'Get Secrets from Encrypted SOPS'
description: 'Simple GitHub Action Helper to extract Azure Service Principal from secrets'
author: 'Thada Wangthammang'
inputs:
  path:
    description: 'Encrypted SOPS yaml path'
    required: true
  property-path:
    description: 'jq/yq expression syntax for getting a particular value'
    required: true
  decrypting-key:
    description: 'A credential using to decrypt a Encrypted SOPS yaml file'
    required: true
  sops-version:
    description: 'Version of sops'
    required: true
    default: 'latest'

outputs:
  secret:
    description: 'The decrypted secret getting from SOPS'
    value: '${{ steps.secret.outputs.result }}'

runs:
  using: 'composite'
  steps:
    - name: Set secret filename
      run: |
        echo "mildronize_action_decrypted_sops_file_age=sops-$(date +%s).yaml" >> $GITHUB_ENV
      shell: bash

    - name: Install Sops
      uses: mdgreenwald/mozilla-sops-action@v1.2.0
      with:
        version: '${{ inputs.sops-version }}'

    - name: Decrypt secrets
      run:
        sops --decrypt "${{ inputs.path }}" > ${{ env.mildronize_action_decrypted_sops_file_age }}
      shell: bash
      env:
        SOPS_AGE_KEY: '${{ inputs.decrypting-key }}'

    - name: Get the key from decrypted SOPS file
      uses: mildronize/actions-yq-secret@main
      id: secret
      with:
        cmd: yq '${{ inputs.property-path }}' ${{ env.mildronize_action_decrypted_sops_file_age }}
        sensitive: true

    - name: Clean tmp files
      run: |
        rm -f ${{ env.mildronize_action_decrypted_sops_file_age }}
      shell: bash
      
branding:
  color: 'gray-dark'
  icon: 'unlock'
