name: "Test SOPS with Azure Key Vault"

on:
  push:
    branches:
      - main
    # paths:
    #   - azure/action.yml

env: 
  expected_result: This is Super secret 

jobs:
  azure-vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mildronize/actions-get-secret-sops/azure@main
        id: sops
        with:
          path: "examples/data.azure-enc.yaml"                     
          property-path: ".scope_a.app_service.app1"              
          decrypting-key: ${{ secrets.Azure_ServicePrinciple_SOPS_github_action }}                 
          sops-version: '3.7.2'
      - run: |
          node ./scripts/compare.js "${{ steps.sops.outputs.secret }}" "${{ env.expected_result }}"
