name: "Test Action"

on:
  push:
  workflow_dispatch:

env: 
  expected_result: This is Super secret 

jobs:
  # read:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install Sops
  #       uses: mdgreenwald/mozilla-sops-action@v1.2.0
  #       with:
  #         version: "3.7.2"
  #     - name: Decrypt secrets
  #       run: sops --decrypt test/plain-text.enc-age.yaml > output.yaml
  #       env:
  #         SOPS_AGE_KEY: ${{ secrets.Age_SOPS_github_action }}
  #     - name: yamler
  #       uses: mildronize/actions-yamler-secrets@main
  #       id: read_yaml
  #       with:
  #         yaml-file: "output.yaml"
  #         add-mark: true
  #     - name: Output Test
  #       run: |
  #         echo "${{ steps.read_yaml.outputs.scope_a__app_service__app1 }}"
  #         echo "${{ toJSON(steps.read_yaml.outputs) }}"
  #     - run: |
  #         node ./scripts/compare.js "${{ steps.read_yaml.outputs.scope_a__app_service__app1 }}" "${{ env.expected_result }}"

  azure-vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mildronize/actions-get-secret-sops@main
        id: sops
        with:
          path: "examples/data.azure-enc.yaml"                     
          property-path: ".scope_a.app_service.app1"              
          decrypting-key: ${{ secrets.Azure_ServicePrinciple_SOPS_github_action }}                 
          sops-version: '3.7.2'
      - run: |
          node ./scripts/compare.js "${{ steps.sops.outputs.secret }}" "${{ env.expected_result }}"
